### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by mw55309** [machinegun/SALSA#12]
Hello!

Just trying this for the first time.

Output is:

```sh
convertng bam file to bed file
finished conversion
finished conversion
started generating links between contigs
bedfile started
bedfile loaded
done generating links between contigs
started scaffolding
Traceback (most recent call last):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/SALSA/links_to_graph3.py", line 457, in <module>
    main()
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/SALSA/links_to_graph3.py", line 103, in main
    v1, v2 = row[0:2]
ValueError: need more than 1 value to unpack
done scaffolding, sequences written to file
```

Output folder contains

```sh
-rw-r--r-- 1 mwatson9 datastore_eb_groups_watson_grp 65854190 Sep  1 19:19 alignment_unique.bed
-rw-r--r-- 1 mwatson9 datastore_eb_groups_watson_grp     2622 Sep  1 19:19 contig_length_new
-rw-r--r-- 1 mwatson9 datastore_eb_groups_watson_grp     2526 Sep  1 19:19 RE_counts
-rw-r--r-- 1 mwatson9 datastore_eb_groups_watson_grp 32423329 Sep  1 19:19 new_links
-rw-r--r-- 1 mwatson9 datastore_eb_groups_watson_grp 32423329 Sep  1 19:20 new_links_sorted
-rw-r--r-- 1 mwatson9 datastore_eb_groups_watson_grp        0 Sep  1 19:20 paths
```

Any idea what is causing this?

Thanks
Mick

**Comment by machinegun** [comment]
Hi Mick,

The links file can be empty. Is your alignment_unique.bed file sorted by read names? Because the code assumes that to construct links.

**Comment by mw55309** [comment]
Hey, sorry, I had turned on some of your debugging code (and figured out the BED sorting thing) and forgot to turn it off!  My apologies.
