### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by jnarayan81** [machinegun/SALSA#42]
It terminated after loading bed file with following error 
```
➜  SALSA git:(master) ✗ python2 run_pipeline.py -a A_plus_collapsed.fa -l A_plus_collapsed.fa.fai -b alignment.bed -e GATC -o scaffolds -i 3
bedfile loaded
Traceback (most recent call last):
  File "/home/urbe/Tools/SALSA/correct.py", line 28, in <module>
    input_seqs = parse_fasta(open(sys.argv[1],'r'))
  File "/home/urbe/Tools/SALSA/correct.py", line 20, in parse_fasta
    for short_name, nuc_list in fa.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

mv: cannot stat 'scaffolds//alignment_iteration_1.tmp.bed': No such file or directory
mv: cannot stat 'scaffolds//asm.cleaned.fasta': No such file or directory
Starting Iteration 1
python /home/urbe/Tools/SALSA/make_links.py -b scaffolds/alignment_iteration_1.bed -d scaffolds -i 1 -x abc
  File "/home/urbe/Tools/SALSA/make_links.py", line 158
    print len(contig_links)
            ^
SyntaxError: invalid syntax

```
How to fix that?

**Comment by machinegun** [comment]
Hi,

Which version of python are you using? The python 3.x doesn't  have `.iteritems()` method defined for dictionary objects. I would recommend using python 2.7 to run SALSA2.

**Comment by jnarayan81** [comment]
Hi @machinegun 
 I am using Python2.7 !

**Comment by bd904** [comment]
I have same issue, can you please write specific command you followd?

**Comment by jnarayan81** [comment]
run_pipeline.py call many python programs, it required Python version2.7
Set the python path https://bioinformaticsonline.com/snippets/view/37505/install-python-locally-on-shared-linux-server
